Pulled latest live-medium-install.

diff --git a/scripts/live-medium-install b/scripts/live-medium-install
--- a/scripts/live-medium-install
+++ b/scripts/live-medium-install
@@ -16,7 +16,10 @@ _VERSION="7.2"
 
 _URL="http://live.debian.net/files/stable/images/${_VERSION}/amd64/webboot/"
 
-_FILES="debian-live-${_VERSION}-amd64-gnome-desktop.vmlinuz debian-live-${_VERSION}-amd64-gnome-desktop.initrd.img debian-live-${_VERSION}-amd64-gnome-desktop.squashfs"
+# Select the default live image config type.
+_CONFIGTYPE="gnome-desktop"
+
+_NONFREE="No, do not include non-free."
 
 _TARGET="/dev/sda"
 
@@ -75,13 +78,80 @@ then
 	exit 1
 fi
 
+cat << EOF
+######################################################
+		live-medium-install
+######################################################
+
+######################################################
+Please enter the image config type to download.
+(default: ${_CONFIGTYPE})
+
+ gnome-desktop
+ kde-desktop
+ lxde-desktop
+ xfce-desktop
+ standard
+ rescue
+
+EOF
+
+# Ask for _CONFIGTYPE
+echo -n ": "
+read _READ
+
+_CONFIGTYPE=${_READ:-${_CONFIGTYPE}}
+
+cat << EOF
+
+######################################################
+Do you want to use images which include the non-free
+arvhive areas? Please enter 'Yes, include non-free.'
+(default: ${_NONFREE})
+
+EOF
+
+# Ask for _NONFREE
+echo -n ": "
+read _READ
+
+_NONFREE=${_READ:-${_NONFREE}}
+
+# Configure _URL and _CONFIGTYPE to include non-free
+case "${_NONFREE}" in
+	'Yes, include non-free.')
+		_URL=$(echo ${_URL} | sed s@${_VERSION}@${_VERSION}+nonfree@)
+		_CONFIGTYPE="${_CONFIGTYPE}+nonfree"
+		;;
+
+	'No, do not include non-free.')
+		;;
+
+	*)
+		echo "Invalid non-free selection of ${_NONFREE} , abort."
+		exit 1
+		;;
+esac
+
+case "${_CONFIGTYPE}" in
+	gnome-desktop|kde-desktop|lxde-desktop|xfce-desktop|standard|rescue|gnome-desktop+nonfree|kde-desktop+nonfree|lxde-desktop+nonfree|xfce-desktop+nonfree|standard+nonfree|rescue+nonfree)
+		_FILES="debian-live-${_VERSION}-amd64-${_CONFIGTYPE}.vmlinuz debian-live-${_VERSION}-amd64-${_CONFIGTYPE}.initrd.img debian-live-${_VERSION}-amd64-${_CONFIGTYPE}.squashfs"
+		;;
+
+	*)
+		echo "Invalid config type. Abort."
+		exit 1
+		;;
+esac
+
+
 # Display warning
 cat << EOF
 ######################################################
 WARNING: This will erase all data on the target device
 ######################################################
 
-Please enter URL to download the ${_IMAGE_FILE} image from
+Please enter URL to download the ${_FILES} from
 (default: ${_URL})
 EOF
 
@@ -142,7 +212,7 @@ echo "Starting dd command for short zero fill..."
 dd if=/dev/zero of=${_TARGET} bs=1024 count=1024
 
 # Make a single partition
-echo "Starting parted command to make lablel and partition..."
+echo "Starting parted command to make label and partition..."
 #parted -s -a optimal ${_TARGET} mklabel gpt -- mkpart primary ext4 1 -1
 #parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 3000
 #parted -s -a optimal ${_TARGET} -- mkpart primary ext4 3000 -1
